"""CVE-style report and PR-body rendering. Never opens a PR itself — cli.py
does that, gated behind --open-pr. By default this only writes files to disk
and returns the exact git/gh commands the operator would run to publish.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from secfix.findings import Finding
from secfix.oracle.sqli import OracleResult
from secfix.patch import PatchApplyResult
from secfix.repo import HarnessTarget


def _redact_sentinel(sql: str, sentinel: str) -> str:
    return sql.replace(sentinel, "<TAINTED_INPUT>")


def build_report(
    finding: Finding,
    target: HarnessTarget,
    oracle_result: OracleResult,
    sentinel: str,
    patch_result: Optional[PatchApplyResult],
) -> str:
    offending_sql = oracle_result.offending_sql or ""
    redacted_sql = _redact_sentinel(offending_sql, sentinel) if offending_sql else "N/A"

    lines = [
        f"# SQL Injection: {target.function_name} ({finding.file_path})",
        "",
        "## Summary",
        f"secfix reproduced a SQL-injection finding (`{finding.rule_id}`) at runtime by "
        f"passing a unique tainted sentinel into `{target.function_name}` and observing it "
        "land, unescaped, inside an executed SQL string. This is a runtime confirmation, "
        "not a static-analysis inference.",
        "",
        "## Affected component",
        f"- File: `{finding.file_path}`",
        f"- Function: `{target.function_name}` (module `{target.module_import_path}`)",
        f"- Lines: {target.lineno}-{target.end_lineno}",
        f"- Tainted parameter: `{target.tainted_param}`"
        + (
            " (assumed — not directly attributable from the finding span)"
            if target.tainted_param_assumed
            else ""
        ),
        "",
        "## Impact",
        "An attacker who controls the tainted parameter can inject arbitrary SQL, "
        "potentially reading, modifying, or deleting data beyond the query's intended "
        "scope, or bypassing application logic enforced only at the query level.",
        "",
        "## Reproduction",
        "1. A unique sentinel (`SECFIX_TAINT_<8hex>`, redacted below as `<TAINTED_INPUT>`) "
        "was passed as the tainted argument.",
        "2. The function's DB access path was replaced with a recording mock — no real "
        "database, network, or seed data was used.",
        "3. The mock observed the following query executed with the sentinel interpolated "
        "directly into the SQL text (not passed as a bound parameter):",
        "",
        "```sql",
        redacted_sql,
        "```",
        "",
        f"Oracle verdict: **{oracle_result.verdict}** — {oracle_result.detail}",
        "",
    ]

    if patch_result is not None:
        lines += [
            "## Fix",
            patch_result.explanation or "(no explanation provided by the model)",
            "",
            "```diff",
            patch_result.diff,
            "```",
            "",
            "## Verification",
            f"Patch status: **{patch_result.kind}** — {patch_result.detail}",
            "",
            "## Residual risk / notes",
            patch_result.notes or "None noted.",
            "",
        ]
    else:
        lines += ["## Fix", "No patch was generated for this report.", ""]

    return "\n".join(lines)


def build_pr_body(finding: Finding, target: HarnessTarget, patch_result: PatchApplyResult) -> str:
    return (
        f"## SQL injection fix: `{target.function_name}` in `{finding.file_path}`\n\n"
        "secfix reproduced this finding at runtime (see attached report) and generated "
        "and verified a fix via the same trace-based oracle.\n\n"
        f"**Verification:** {patch_result.kind} — {patch_result.detail}\n\n"
        f"### What changed\n{patch_result.explanation}\n\n"
        f"### Residual risk\n{patch_result.notes or 'None noted.'}\n\n"
        "---\n"
        "_Generated by secfix. Review before merging._\n"
    )


@dataclass
class DiskOutput:
    report_path: Path
    pr_body_path: Optional[Path]
    next_steps: str


def write_report_to_disk(
    output_dir: Path,
    report_text: str,
    branch_name: str,
    pr_body: Optional[str] = None,
    open_pr: bool = False,
) -> DiskOutput:
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / "report.md"
    report_path.write_text(report_text)

    pr_body_path = None
    if pr_body is not None:
        pr_body_path = output_dir / "pr_body.md"
        pr_body_path.write_text(pr_body)

    if open_pr:
        next_steps = "PR creation was requested (--open-pr); see CLI output above for status."
    elif pr_body_path:
        # pr_body is only ever built by the caller for a `validated` patch —
        # this is the ONLY branch where a push/PR command is suggested, even
        # in text. A branch that exists but didn't validate must never come
        # with a publish suggestion attached, printed or otherwise.
        push_cmd = f"git push -u origin {branch_name}"
        gh_cmd = (
            f'gh pr create --title "secfix: SQL injection fix ({branch_name})" '
            f"--body-file {pr_body_path}"
        )
        next_steps = (
            "Dry run: no PR was opened. To publish this validated fix, run:\n\n"
            f"  {push_cmd}\n"
            f"  {gh_cmd}\n"
        )
    elif branch_name:
        next_steps = (
            f"Scratch branch '{branch_name}' was created locally with an unverified/failed "
            "patch attempt for manual inspection. It has NOT been pushed and no publish "
            "command is suggested — re-verification did not confirm the fix."
        )
    else:
        next_steps = "No patch was applied; nothing to publish."

    return DiskOutput(report_path=report_path, pr_body_path=pr_body_path, next_steps=next_steps)
